import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const seed=[
{id:'demo1',title:'Smart Campus Navigation',description:'A campus app showing accessible routes, crowded areas and classroom changes in real time.',category:'Technology',author:'Aarav Shah',votes:128,comments:18,team:3,tags:['React','Maps','Campus'],trend:96},
{id:'demo2',title:'Food Rescue Network',description:'Connect canteens, hostels and NGOs to redistribute safe surplus food before it is wasted.',category:'Social Impact',author:'Meera Patel',votes:104,comments:12,team:4,tags:['Food','Impact','NGO'],trend:91},
{id:'demo3',title:'Study Battle',description:'Students challenge friends to timed quizzes and climb a live knowledge leaderboard.',category:'Education',author:'Rohan Mehta',votes:87,comments:9,team:2,tags:['Quiz','Game','Learning'],trend:88},
{id:'demo4',title:'SkillSwap',description:'Find someone who can teach the skill you want while offering a skill of your own.',category:'Community',author:'Nisha Verma',votes:76,comments:15,team:5,tags:['Skills','Match','Chat'],trend:83}
];
const initials=n=>(n||'U').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
const api=async(path,options={})=>{const token=localStorage.getItem('ideaarena-token');const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Something went wrong');return d};
function App(){
 const [page,setPage]=useState('Discover'),[ideas,setIdeas]=useState(seed),[user,setUser]=useState(null),[showAuth,setShowAuth]=useState(false),[mode,setMode]=useState('login'),[resetToken,setResetToken]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[cat,setCat]=useState('All'),[sort,setSort]=useState('Trending'),[showPitch,setShowPitch]=useState(false),[newIdea,setNewIdea]=useState({title:'',description:'',category:'Technology',tags:''}),[selected,setSelected]=useState(null),[comments,setComments]=useState([]),[comment,setComment]=useState(''),[leaderboard,setLeaderboard]=useState([]),[profileOpen,setProfileOpen]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('ideaarena-dark')==='1'),[saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('ideaarena-saved')||'[]')),[loading,setLoading]=useState(false);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 useEffect(()=>{const t=new URLSearchParams(location.search).get('reset');if(t){setResetToken(t);setMode('reset');setShowAuth(true)}},[]);
 useEffect(()=>{document.body.classList.toggle('dark',dark);localStorage.setItem('ideaarena-dark',dark?'1':'0')},[dark]);
 useEffect(()=>{localStorage.setItem('ideaarena-saved',JSON.stringify(saved))},[saved]);
 useEffect(()=>{(async()=>{try{const d=await api('/api/ideas');if(d.ideas?.length)setIdeas(d.ideas)}catch{}})();const t=localStorage.getItem('ideaarena-token');if(t)api('/api/auth/me').then(d=>setUser(d.user)).catch(()=>localStorage.removeItem('ideaarena-token'));},[]);
 useEffect(()=>{if(page==='Leaderboard')api('/api/users/leaderboard').then(d=>setLeaderboard(d.users)).catch(()=>{})},[page]);
 const categories=['All',...new Set(ideas.map(i=>i.category))];
 const filtered=useMemo(()=>ideas.filter(i=>(`${i.title} ${i.description} ${(i.tags||[]).join(' ')}`).toLowerCase().includes(query.toLowerCase())&&(cat==='All'||i.category===cat)).sort((a,b)=>sort==='Newest'?new Date(b.createdAt||0)-new Date(a.createdAt||0):(b.trend||0)-(a.trend||0)),[ideas,query,cat,sort]);
 const requireLogin=()=>{if(!user){setMode('login');setShowAuth(true);return false}return true};
 const authSubmit=async e=>{e.preventDefault();setError('');setLoading(true);try{if(mode==='reset'){const d=await api('/api/auth/reset-password',{method:'POST',body:JSON.stringify({token:resetToken,password})});setMode('login');setPassword('');setShowAuth(false);history.replaceState({},'',location.pathname);notify(d.message)}else{const d=await api(mode==='signup'?'/api/auth/signup':'/api/auth/login',{method:'POST',body:JSON.stringify(mode==='signup'?{name,email,password}:{email,password})});localStorage.setItem('ideaarena-token',d.token);setUser(d.user);setShowAuth(false);setName('');setPassword('');notify(mode==='signup'?`Welcome, ${d.user.name}! 🎉`:`Welcome back, ${d.user.name}! 👋`)}}catch(e){setError(e.message)}finally{setLoading(false)}};
 const forgot=async()=>{if(!email)return setError('Enter your email first.');try{const d=await api('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});notify(d.message)}catch(e){setError(e.message)}};
 const logout=()=>{localStorage.removeItem('ideaarena-token');setUser(null);setProfileOpen(false);notify('You have been logged out.');setPage('Discover')};
 const vote=async idea=>{if(!requireLogin())return;try{const d=await api(`/api/ideas/${idea._id||idea.id}/vote`,{method:'POST'});setIdeas(x=>x.map(i=>(i._id||i.id)===(idea._id||idea.id)?d.idea:i));notify('Vote added! +1 🚀')}catch(e){notify(e.message)}};
 const publish=async e=>{e.preventDefault();if(!requireLogin())return;try{const d=await api('/api/ideas',{method:'POST',body:JSON.stringify({...newIdea,tags:newIdea.tags.split(',').map(x=>x.trim()).filter(Boolean)})});setIdeas(x=>[d.idea,...x]);setNewIdea({title:'',description:'',category:'Technology',tags:''});setShowPitch(false);setPage('My Ideas');notify('Idea published 🚀')}catch(e){notify(e.message)}};
 const openIdea=async idea=>{setSelected(idea);setComments([]);try{const d=await api(`/api/ideas/${idea._id||idea.id}/comments`);setComments(d.comments)}catch{}};
 const sendComment=async e=>{e.preventDefault();if(!requireLogin()||!comment.trim())return;try{const d=await api(`/api/ideas/${selected._id||selected.id}/comments`,{method:'POST',body:JSON.stringify({text:comment})});setComments(x=>[...x,d.comment]);setComment('');setIdeas(x=>x.map(i=>(i._id||i.id)===(selected._id||selected.id)?{...i,comments:(i.comments||0)+1}:i))}catch(e){notify(e.message)}};
 const myIdeas=ideas.filter(i=>String(i.authorId)===String(user?.id)||String(i.authorId)===String(user?._id));
 return <div className="app"><header className="header"><button className="logo" onClick={()=>setPage('Discover')}>✦ IdeaArena</button><nav>{['Discover','Leaderboard','My Ideas','Saved'].map(x=><button key={x} className={page===x?'navActive':''} onClick={()=>setPage(x)}>{x}</button>)}</nav><div className="headerRight"><button className="iconButton" onClick={()=>setDark(!dark)}>{dark?'☀️':'🌙'}</button>{user?<div className="profileWrap"><button className="profileButton" onClick={()=>setProfileOpen(!profileOpen)}><span className="avatar">{initials(user.name)}</span></button>{profileOpen&&<div className="profileMenu"><b>{user.name}</b><small>{user.email}</small><button onClick={()=>{setPage('Profile');setProfileOpen(false)}}>My Profile</button><button onClick={logout}>Logout</button></div>}</div>:<button className="primary small" onClick={()=>{setMode('login');setShowAuth(true)}}>Login</button>}</div></header>
 <main>{page==='Discover'&&<><section className="hero"><div><div className="eyebrow">THE NEXT BIG IDEA STARTS HERE</div><h1>Think it. <span>Share it.</span><br/>Build it together.</h1><p>IdeaArena is your creative space to discover ideas, get feedback, find teammates and turn great concepts into real projects.</p><div className="heroActions"><button className="primary" onClick={()=>{if(requireLogin())setShowPitch(true)}}>＋ Pitch an Idea</button><button className="secondary" onClick={()=>document.getElementById('ideaGrid')?.scrollIntoView({behavior:'smooth'})}>Explore Ideas</button></div></div><div className="heroCard"><div className="spark">✦</div><b>Ideas are better together.</b><p>Share your concept and let the community help you make it stronger.</p><div className="miniPeople"><span>AS</span><span>MP</span><span>RM</span><span>NV</span></div></div></section><section className="toolbar"><div className="searchBox">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ideas, tags or people..."/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option>Trending</option><option>Newest</option></select></section><div className="chips">{categories.map(x=><button className={cat===x?'chip active':'chip'} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><section id="ideaGrid" className="grid">{filtered.map(idea=><IdeaCard key={idea._id||idea.id} idea={idea} onVote={()=>vote(idea)} onOpen={()=>openIdea(idea)} saved={saved.includes(idea._id||idea.id)} onSave={()=>{if(!requireLogin())return;const id=idea._id||idea.id;setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);notify('Saved for later ❤️')}}/>)}</section></>}
 {page==='Leaderboard'&&<section className="leaderboard"><h2>Community leaderboard 🏆</h2><p>The creators getting the most love from the IdeaArena community.</p>{leaderboard.map((u,i)=><div className="rank" key={u._id}><strong>#{i+1}</strong><span className="avatar">{initials(u.name)}</span><div><b>{u.name}</b><small>{u.ideas||0} ideas · {u.email}</small></div><em>▲ {u.votes||0} votes</em></div>)}</section>}
 {page==='My Ideas'&&<><div className="pageHead"><div><h2>My Ideas</h2><p className="muted">Your published concepts in one place.</p></div><button className="primary" onClick={()=>{if(requireLogin())setShowPitch(true)}}>＋ New idea</button></div><section className="grid">{myIdeas.length?myIdeas.map(i=><IdeaCard key={i._id} idea={i} onVote={()=>vote(i)} onOpen={()=>openIdea(i)} saved={saved.includes(i._id)} onSave={()=>{}}/>):<div className="empty"><div>✦</div><h3>No ideas yet</h3><p>Publish your first idea and get the community talking.</p><button className="primary" onClick={()=>{if(requireLogin())setShowPitch(true)}}>Pitch your first idea</button></div>}</section></>}
 {page==='Saved'&&<><div className="pageHead"><div><h2>Saved Ideas</h2><p className="muted">Ideas you want to come back to.</p></div></div><section className="grid">{ideas.filter(i=>saved.includes(i._id||i.id)).map(i=><IdeaCard key={i._id||i.id} idea={i} onVote={()=>vote(i)} onOpen={()=>openIdea(i)} saved onSave={()=>setSaved(s=>s.filter(x=>x!==(i._id||i.id)))}/>)}</section>{!ideas.some(i=>saved.includes(i._id||i.id))&&<div className="empty"><div>♡</div><h3>Your saved ideas will appear here</h3></div>}</>}
 {page==='Profile'&&user&&<Profile user={user} onLogout={logout} onUpdated={u=>setUser(u)}/>}</main><footer>IdeaArena Pro · Built with React, Node.js, MongoDB & secure email</footer>
 {showAuth&&<div className="modalBackdrop"><div className="modal authForm"><div className="modalHeader"><div><div className="authBrand">✦ IdeaArena</div><h2>{mode==='signup'?'Create your account':mode==='reset'?'Set a new password':'Welcome back'}</h2><p className="muted">{mode==='signup'?'Join the community and make your ideas visible.':mode==='reset'?'Choose a new password for your IdeaArena account.':'Sign in to vote, publish and connect.'}</p></div><button onClick={()=>setShowAuth(false)}>×</button></div><form className="pitchForm" onSubmit={authSubmit}>{mode==='signup'&&<label>Username<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your display name" required/></label>}{mode!=='reset'&&<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label>}<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters" required/></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?'Please wait...':mode==='signup'?'Create account':mode==='reset'?'Update password':'Login'}</button></form>{mode==='login'&&<button className="linkButton" onClick={forgot}>Forgot password? Email me a reset link</button>}{mode!=='reset'&&<div className="authSwitch">{mode==='signup'?'Already have an account?':'New to IdeaArena?'} <button onClick={()=>{setMode(mode==='signup'?'login':'signup');setError('')}}>{mode==='signup'?'Login':'Create account'}</button></div>}<small className="setupHint">Your username is shown on your profile and beside your ideas.</small></div></div>}
 {showPitch&&<div className="modalBackdrop"><div className="modal"><div className="modalHeader"><div><h2>Pitch your idea 🚀</h2><p className="muted">Make it clear, useful and easy to understand.</p></div><button onClick={()=>setShowPitch(false)}>×</button></div><form className="pitchForm" onSubmit={publish}><label>Idea title<input value={newIdea.title} onChange={e=>setNewIdea({...newIdea,title:e.target.value})} required placeholder="e.g. Smart Study Buddy"/></label><label>Description<textarea value={newIdea.description} onChange={e=>setNewIdea({...newIdea,description:e.target.value})} required placeholder="What problem does it solve?"/></label><label>Category<select value={newIdea.category} onChange={e=>setNewIdea({...newIdea,category:e.target.value})}><option>Technology</option><option>Education</option><option>Social Impact</option><option>Community</option><option>Business</option></select></label><label>Tags<input value={newIdea.tags} onChange={e=>setNewIdea({...newIdea,tags:e.target.value})} placeholder="React, AI, Students"/></label><button className="primary wide">Publish idea</button></form></div></div>}
 {selected&&<div className="modalBackdrop"><div className="modal chatModal"><div className="modalHeader"><div><span className="category">{selected.category}</span><h2>{selected.title}</h2><p className="muted">By <b>{selected.author}</b></p></div><button onClick={()=>setSelected(null)}>×</button></div><p>{selected.description}</p><div className="discussion">{comments.length?comments.map(c=><div className="comment" key={c._id}><span className="avatar">{initials(c.sender)}</span><div><b>{c.sender}</b><p>{c.text}</p></div></div>):<div className="noChat">No comments yet.<br/>Be the first to start the discussion.</div>}</div><form className="chatInput" onSubmit={sendComment}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder={user?'Add a thoughtful comment...':'Login to comment'}/><button className="primary">Send</button></form></div></div>}
 {toast&&<div className="toast">{toast}</div>}</div>}
function IdeaCard({idea,onVote,onOpen,saved,onSave}){return <article className="ideaCard"><div className="cardTop"><span className="category">{idea.category}</span><button className={saved?'saveButton saved':'saveButton'} onClick={onSave}>{saved?'♥':'♡'}</button></div><h2>{idea.title}</h2><p>{idea.description}</p><div className="tags">{(idea.tags||[]).map(t=><span key={t}>#{t}</span>)}</div><div className="author"><span className="avatar">{initials(idea.author)}</span><div className="authorText"><b>{idea.author}</b><small>Idea creator</small></div><span className="team">👥 {idea.team||1}</span></div><div className="cardBottom"><button className="voteButton" onClick={onVote}>▲ {idea.votes||0}</button><span>💬 {idea.comments||0}</span><button className="openButton" onClick={onOpen}>Discuss →</button></div></article>}
function Profile({user,onLogout,onUpdated}){const [n,setN]=useState(user.name),[bio,setBio]=useState(user.bio||''),[msg,setMsg]=useState('');const save=async e=>{e.preventDefault();try{const d=await api('/api/users/me',{method:'PUT',body:JSON.stringify({name:n,bio})});onUpdated(d.user);setMsg('Profile updated ✓')}catch(e){setMsg(e.message)}};return <section><div className="profileHero"><span className="bigAvatar">{initials(user.name)}</span><div><h2>{user.name}</h2><p>{user.email}</p><div className="profileStats"><span><b>IdeaArena</b> member</span></div></div><button className="secondary" onClick={onLogout}>Logout</button></div><div className="editProfile"><h3>Edit profile</h3><form className="pitchForm" onSubmit={save}><label>Username<input value={n} onChange={e=>setN(e.target.value)} required/></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="Tell the community what you build..."/></label><button className="primary">Save profile</button></form>{msg&&<p className="muted">{msg}</p>}</div></section>}
createRoot(document.getElementById('root')).render(<App/>);
